version: '3.4'
services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "4848:4848"
    restart: on-failure
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/
      - keycloak-client.server-url=http://localhost:18080/auth
    depends_on:
      - discovery-service
  discovery-service:
    build:
      context: ./discovery-service
    ports:
      - "8761:8761"
    restart: on-failure
  user-service:
    build:
      context: ./user-service
    ports:
      - "8081:8081"
    restart: on-failure
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/
      - keycloak-client.server-url=http://localhost:18080/auth
    depends_on:
      - discovery-service
  rating-service:
    build:
      context: ./rating-service
    ports:
      - "8089:8089"
    restart: on-failure
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/
      - keycloak-client.server-url=http://localhost:18080/auth
    depends_on:
      - discovery-service
  keycloak:
    image: jboss/keycloak:11.0.0
    volumes:
      - ./authentication-service/realm-export.json:/tmp/keycloak/config/realm-export.json
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/keycloak/config/realm-export.json
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
    ports:
      - "18080:18080"
    command:
      - "-b"
      - "0.0.0.0"
      - "-Djboss.socket.binding.port-offset=10000"
    restart: on-failure
    depends_on:
      - postgres
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
volumes:
  postgres_data:
    name: keycloak_postgres_data
    driver: local